# For more information: https://laravel.com/docs/sail
version: '3'
services:
    statamic.bug.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            SSH_AUTH_SOCK: /ssh-agent
        volumes:
            - '.:/var/www/html'
            - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
            - '~/.composer/auth.json:/home/sail/.composer/auth.json:delegated' # Composer personal token
        networks:
            - sail
networks:
    sail:
        driver: bridge